PLAYER-MESSAGES:
  ACCEPT: "&6&lЗАЩИТА: &fПодтвердите авторизацию через телеграм."
  ACCEPTED: "&6&lЗАЩИТА: &fВаша авторизация подтверждена."
  CANCEL-COMMAND: "kick {name} отказ"

ADMIN-MESSAGES:
  ACCEPT: "&6&lАДМИН-ИНФА: &fАдминистратору &6&l{name} &fнеобходимо пройти авторизацию."
  ACCEPTED: "&6&lАДМИН-ИНФА: &fАдминистратор &6&l{name} &fпрошёл авторизацию."
  BAN: "&6&lАДМИН-ИНФА: &fАвторизация администратора &6&l{name} &fне была подтверждена."

TG-SETTINGS:
  BOT-KEY: "5123598144:AAEldy02Lyx8KFHDgnDlR-kviUof5-aphF4"
  CHAT-ID: "-1001715422338"
  ACCEPT: "✅ Администратор @{user} авторизировал {name}"
  CANCEL: "❌ Администратор @{user} заблокировал {name}"
  MESSAGE: |
    ‼️ ВНИМАНИЕ ‼️

    🔒 Подтвердите авторизацию игрока

    ⚠️ Игрок владеет правами администратора ⚠️
    🔍 Адрес: {address}
    🥷🏼 Ник: {name}
    🎮 Режим: {server}